#运行参数详解
#-s: 表示输出调试信息，包括print打印的信息
#-v: 显示更详细的信息
#-vs: 两参数可以一起使用
#-n: 支持多线程或者分布式运行测试用例（'-n=2'）
#--reruns: 失败用例重跑（'--reruns=2'）
#-x: 表示只要有一个用例报错就停止测试，后面的用例不运行
#--maxfail: 出现两个失败用例就停止（'--maxfail=2'）
#-k:根据测试用例名称的部分字符串运行测试用例（'-k=demo'）
#-m 实现分组，实际应用'-m=cat or dog'
